# Form implementation generated from reading ui file 'RegForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(371, 271)
        Form.setStyleSheet("background-color: rgb(211, 209, 208);\n"
"color: rgb(0, 85, 255);\n"
"font: 75 14pt \"Gill Sans MT\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.LoginLabel = QtWidgets.QLabel(parent=Form)
        self.LoginLabel.setObjectName("LoginLabel")
        self.verticalLayout.addWidget(self.LoginLabel)
        self.LoginEdit = QtWidgets.QLineEdit(parent=Form)
        self.LoginEdit.setObjectName("LoginEdit")
        self.verticalLayout.addWidget(self.LoginEdit)
        self.PasswordLabel = QtWidgets.QLabel(parent=Form)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.verticalLayout.addWidget(self.PasswordLabel)
        self.PasswordEdit = QtWidgets.QLineEdit(parent=Form)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.verticalLayout.addWidget(self.PasswordEdit)
        self.EnterButton = QtWidgets.QPushButton(parent=Form)
        self.EnterButton.setObjectName("EnterButton")
        self.verticalLayout.addWidget(self.EnterButton)
        self.CloseButton = QtWidgets.QPushButton(parent=Form)
        self.CloseButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.CloseButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Advertising Agency"))
        self.LoginLabel.setText(_translate("Form", "Логин"))
        self.PasswordLabel.setText(_translate("Form", "Пароль"))
        self.EnterButton.setText(_translate("Form", "Войти"))
        self.CloseButton.setText(_translate("Form", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
